services:
  reverse_proxy:
    build: reverse-proxy
    image: ghcr.io/williamsnell/reverse-proxy
    volumes:
      - ./reverse-proxy/playhexchess.com:/etc/nginx/sites-available/playhexchess.com
    ports:
      - 80:80
      - 443:443
  playhexchess:
    build: playhexchess
    image: ghcr.io/williamsnell/playhexchess

