services:
  reverse_proxy:
    build: reverse-proxy
    image: ghcr.io/williamsnell/reverse-proxy
    volumes:
      - ./reverse-proxy/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
  playhexchess:
    build: playhexchess
    image: ghcr.io/williamsnell/playhexchess

