services:
  reverse-proxy:
    build: reverse-proxy
    image: ghcr.io/williamsnell/reverse-proxy
    volumes:
      - ./reverse-proxy/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
  playhexchess:
    hostname: playhexchess
    build: playhexchess
    image: ghcr.io/williamsnell/playhexchess
    volumes: 
      - ./playhexchess/playhexchess.conf:/etc/nginx/conf.d/default.conf
      - ./playhexchess/entrypoint.sh:/entrypoint.sh
  willsnell:
    hostname: willsnell
    image: nginx
    volumes:
      - ./willsnell/willsnell.com:/etc/nginx/sites-enabled/willsnell.com
      - ./willsnell/data:/data
